# Generated by Django 2.2.2 on 2019-06-22 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('vid', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('html', models.TextField()),
                ('shared_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'youtube_video',
            },
        ),
    ]
