# Generated by Django 2.2.2 on 2019-06-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='id',
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='vid',
            field=models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
