# Generated by Django 2.2.2 on 2019-06-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_youtubevideo_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='description',
            field=models.TextField(default='Video description here.'),
        ),
    ]
