# Generated by Django 2.2.2 on 2019-06-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_youtubevideo_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='author_url',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
